server:
  port: 8114
spring:
  application:
    name: device-gather-tcp
  rabbitmq:
    #host: 172.17.0.1
    host: 192.168.1.79
    port: 5672
    username: cnten
    password: cnten
  datasource:
    name: data-source
    url: jdbc:mysql://192.168.1.104:3307/bd_message?useUnicode=true&characterEncoding=utf-8&useOldAliasMetadataBehavior=true&serverTimezone=UTC
    username: bd_message
    password: bd_message
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.201
    port: 6379
    password: ''
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
cache:
  data-key: device-cache-data
vertx: 
  worker:
    pool:
      size: 60
  springWorker:
    instances: 30
  http:
    port: 20002
    address: 0.0.0.0
queue:
  name: bd_zhoujf

mybatis:
  xmlLocation: classpath:com/cnten/platform/**/mapping/*.xml
  mapper-locations: "classpath*:com/cnten/platform/**/mapping/*.xml"
    #configuration:
  #map-underscore-to-camel-case: true

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  identity: mysql
  before: false
  style: camelhumpandlowercase

logging:
  level:
    com.cnten.platform: debug

backFlag:
  isBack: true